services:
  - type: web
    name: monkeychat-backend
    env: go
    buildCommand: cd backend && go build -o main .
    startCommand: cd backend && ./main
    envVars:
      - key: TIDB_HOST
        sync: false
      - key: TIDB_PORT
        sync: false
      - key: TIDB_USER
        sync: false
      - key: TIDB_PASSWORD
        sync: false
      - key: TIDB_DATABASE
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://monkeychat-ela7.onrender.com
      - key: PORT
        value: 8080
      - key: BASE_URL
        value: https://monkeychat-ela7.onrender.com
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        sync: false
      - key: VITE_BASE_URL
        value: https://monkeychat-ela7.onrender.com

  - type: web
    name: monkeychat-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview -- --host 0.0.0.0 --port 3000
    envVars:
      - key: VITE_BASE_URL
        value: https://monkeychat-ela7.onrender.com
      - key: PORT
        value: 3000
      - key: BASE_URL
        value: https://monkeychat-ela7.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 